### ISSUE TITLE
Hiding replies in addition to retweets

### ISSUE THREAD

**Issue by patrikarvidsson** [mc72/Bluebird-statamic-v2#3]
Is it possible to hide replies?

**Comment by mc72** [comment]
Sorry, don't use this anymore (although should work just fine).  There are a couple modifiers you can use:

 $include_rts  = $this->getBool('include_rts', true);   
 $exclude_replies  = $this->getBool('exclude_replies', false);

Just put those in your tag and set the first to false, the second to true and it should work.  (Again I didn't actually build it, just did an early conversion from a V1 addon to V2).
